#!/usr/bin/env bash
#Configures the domain zone so that the subdomain www points to your load-balancer IP (lb-01).

display_info() {
    local subdomain=$1
    local domain=$2
    local record_type=$3
    local destination=$4

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

audit_subdomain() {
    local subdomain=$1
    local domain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_info=$(dig +short "$sub.$domain" | awk '{print $1}')

        if [ -n "$record_info" ]; then
            record_type=$(dig +short "$sub.$domain" | awk 'NR==1{print $4}')
            destination=$(dig +short "$sub.$domain")

            display_info "$sub" "$domain" "$record_type" "$destination"
        else
            echo "The subdomain $sub does not exist for $domain"
        fi
    done
}

if [ "$#" -eq 1 ]; then
    audit_subdomain "" "$1"
elif [ "$#" -eq 2 ]; then
    audit_subdomain "$2" "$1"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
