#!/usr/bin/env bash
# This script configures web-02 to be identical to web-01.

sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  Sam-d23_frontend
        bind *:80
        mode http
        default_backend Sam-d23_backend
backend Sam-d23_backend
        balance roundrobin
        server 176572-web-01 52.3.246.65:80 check
        server 176572-web-02 34.224.15.114:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
