#!/bin/bash
#Installs and configures HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy
server_config=\
"
frontend  ehoneah-frontend
        bind *:80
        mode http
        default_backend ehoneah-backend
backend ehoneah-backend
        balance roundrobin
        server 266930-web-01 52.3.246.65:80 check
        server 266930-web-02 34.224.15.114:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
