#!/bin/bash
#Installs and configures HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 266930-web-01 52.3.246.65:80 check
    server 266930-web-02 34.224.15.114:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
