#!/bin/bash
#Installs and configures HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg >/dev/null
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo service haproxy restart
