#!/usr/bin/env bash
#This script lists all running processes
#Showing all processes, for all users, including those which might not have a TTY
#in a user-oriented format showing process hierachy

ps auxf
