#!/usr/bin/env bash
#This script parses Apache log files in list format and
# then  groups visitors by IP and HTTP status code.
#   Displaying the number of occurrences, IP, and HTTP status
# of code of each log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
