#!/bin/usr/env bash
#This script prints "Best School" 10 times but "Hi" after the 9th iteration
tarry=0

while [ $tarry -lt 10 ]
do
  if [ $tarry -eq 8 ]
  then
    echo "Best School"
    echo "Hi"
  fi
  echo "Best School"
  (( tarry++ ))
done
