#!/bin/usr/env bash
#Loops from 1 to 10 printing "Best School" but "bad luck"
#and "good luck" on 4th and 8th iteration respectively

j=1

while [ $j -le 10 ]; do
    if [ $j -eq 4 ]; then
        echo "Bad Luck"
    elif [ $j -eq 8 ]; then
        echo "Good Luck"
    else
        echo "Best School"
    fi

    ((j++))
done
