#!/usr/bin/env bash
# Displays the contents of the current directory as follows in list format:
#   Only the part of the name after the first dash is displayed

list=$(ls)
for j in $list; do
  echo "$j" | cut -d '-' -f2
done

