#!/usr/bin/env bash

# Updates the package manager and installs the requirements
sudo apt update
sudo apt install -y nginx python3-pip net-tools gunicorn
pip3 install flask flask_cors sqlalchemy

#Clones repositories
git clone https://github.com/Sam-d23/AirBnB_clone_v3
git clone https://github.com/Sam-d23/AirBnB_clone_v4

# Configuring Nginx
sudo tee "/etc/nginx/sites-enabled/default" > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location /hbnb_static { 
        alias /data/web_static/current/;
    }
    location /static/ {
        alias /home/ubuntu/AirBnB_clone_v4/web_dynamic/static/;
        try_files \$uri \$uri/ =404;
    }
    location / {
        proxy_pass http://0.0.0.0:5003;
    }
    location /airbnb-onepage {
        proxy_pass http://0.0.0.0:5000/airbnb-onepage;
    }
    location ~ ^/airbnb-dynamic/number_odd_or_even/([0-9]+)$ {
        proxy_pass http://0.0.0.0:5001/number_odd_or_even/\$1;
    }
    location /api/ {
        proxy_pass http://0.0.0.0:5002;
    }
    if (\$request_filename ~ redirect_me){
        rewrite ^ https://th3-gr00t.tk/ permanent;
    }
    error_page 404 /error_404.html;
    location = /error_404.html {
        internal;
    }
}
EOF

# Restarting Nginx
sudo systemctl restart nginx

# Setting up tmux sessions
cd /home/ubuntu/AirBnB_clone_v3 && tmux new-session -d 'gunicorn --bind 0.0.0.0:5002 api.v1.app:app'
cd /home/ubuntu/AirBnB_clone_v4 && git checkout app-server

echo "Task complete"

